### ISSUE TITLE
Search useless on a sunny day

### ISSUE THREAD

**Issue by jidanni** [deadlyjack/Acode#203]
Because the search identifier uses a gray block upon a black background, it's very hard to see on a sunny day.

So how about orange?

**Comment by tukusejssirs** [comment]
Indeed the colours should be more contrasting. I use black theme and wish the users could change any and all colours and thus create custom themes.

**Comment by deadlyjack** [comment]
Please can you provide more information about this issue like a screenshot.

**Comment by tukusejssirs** [comment]
Here you go. I use black theme and the selection colour and the background colour are not enough contras5ing. The selection colour should be lighter than bg colour on dark/black themes.

IMHO the whole black theme should be revised or even better: let the users choose their prefered colours.

<img src="https://user-images.githubusercontent.com/5111894/120864503-9ae93480-c58c-11eb-83fc-94bd4f7e0688.jpg" width="48%"> <img src="https://user-images.githubusercontent.com/5111894/120864508-9cb2f800-c58c-11eb-9245-202004a0dc80.jpg" width="48%">

**Comment by tukusejssirs** [comment]
I think this has been fixed in `v1.3.155`. In my case, I lost the session (open files) open before the upgrade, therefore I suggest to backup anything you need prior to upgrade.

I even found an option to change (some/most of) the colours in Menu → Settings → Themes → App (tab) → Custom. Thanks, @deadlyjack!

Some stuff still could be improved, but I think it is much more usable now. :wink:
