### ISSUE TITLE
Some problems - Maybe permissions?

### ISSUE THREAD

**Issue by Micha-he** [deadlyjack/Acode#273]
1. I can't see any files/folders under 'Internal Storage'. Another new link to the same place works.

2. Files which are opened via Total Commander from any (int/ext sdcard) place, isn't displayed in Acode. 

All with new installed Motorola One Vision under Android 10. Second phone with Android 9 and multiple updated Acode Installation, seems to work flawlessly.

Other test with a different editor works with TC.

**Comment by Serpolet** [comment]
I have the same issue on Samsung Galaxy A31 running Android 10 with Acode version 1.4.164 . Unable to open an existing code file from my file browser, nor to access my files from within Acode.

**Comment by deadlyjack** [comment]
Have you tried clearing app data?

**Comment by Micha-he** [comment]
Yes, no difference.

Even a re-installation didn't bring any improvement.

**Comment by another-sapiens** [comment]
It's also not allowing CSS or images referenced in the HTML to be displayed.

It's got something to do with the paths. If you open a file (by pressing the 3 dots on the top right and selecting "Files") and take a look at the path (on the main screen, below the file title), there's a `%2` instead of a `/` between every folder. 

As a workaround, if you downgrade to release `1.2.143` (where the bug this issue reports is not present) and select the folder with the files as intended, you can then update to the latest version and keep that folder at reach. The path no longer shows `%2` after selecting them from that folder and the HTML references start working, allowing the CSS to be previewed again.

**Comment by unixpeikko** [comment]
Apparently same issue with Android 10 on  Galaxy Tab A (2018, 10.5)
- Nothing from internal storage is visible and it  shows as "Empty Folder" 
- It's possible to create a folder from Acode under INTERNAL STORAGE, but created folder is not visible for other programs.
- file:///storage/emulated/0/ is not accessible from Acode and Save As results in "ERROR Invalid modification"
- It's possible to edit files shared files from Termux via Insert file functionality via "Select document"-folder by selecting "FILES FROM TERMUX"

**Comment by lmagyar** [comment]
Android 8, Galaxy A3
After opening and editing a file, when I try to save: "Path not found"

**Comment by Micha-he** [comment]
The problem still exists with the latest version!

**Comment by rons4** [comment]
For me on a Samsung Galaxy Tab S4 with Android 10 I can access the files now with the latest version. Thanks a lot.

**Comment by Micha-he** [comment]
Yes, at me too.

I've uninstalled the version that didn't work, so reinstall the new/last version, reconfigure it and grant permissions again.

So it could have been due to a variety of reasons in my side...
