### ISSUE TITLE
[Feature Request] Add LSP support for multiple programming languages.

### ISSUE THREAD

**Issue by mystique09** [deadlyjack/Acode#339]
Hi, I would like to request for LSP support for this app if it's possible, just like in lunarvim. LSP is a great feature.

**Comment by deadlyjack** [comment]
Thank you for your suggestion. I'll find a way to implement it next versions.

**Comment by schwrzstrbn** [comment]
Having LSPs such as rust-analyzer and gopls would be cool. I'm looking forward to it. Cheers!

**Comment by xdevelnet** [comment]
I am also looking for support for my favourite language. Do you accept some kind of bounty or something like that? I really would like to have this feature in order to have the following feature for the C language:

1. Go to definition
2. Go to declaration
3. Find usages
4. Syntax highlighting (including syntax error highlighting)

**Comment by bajrangCoder** [comment]
Check out plugins
