### ISSUE TITLE
[Feature Request] Ability to have multiple folders open

### ISSUE THREAD

**Issue by flleeppyy** [deadlyjack/Acode#570]
I'm working on a project that involves a frontend and backend, but i can only open one at a time, and it's a bit annoying to constantly change the open folder. I don't want to open the parent directory because.. well it doesn't make sense,and its more cluttered trying to find my project.

Could we possibly get the ability to open multiple folders?

**Comment by deadlyjack** [comment]
Sorry, I didn't get it. Can you explain a little bit more please.

**Comment by flleeppyy** [comment]
You can only open one folder in Acode. If you want to be able to access multiple folders, you have to open a directory that has the folders you want to access

**Comment by flleeppyy** [comment]
![Screenshot_20221201-124342_Acode.jpg](https://user-images.githubusercontent.com/18307183/205155675-a9d0072a-3c71-4ab9-b13d-4d0ae0cacc62.jpg)

Theres only one folder here. if you want to open a different folder, you click the X button, but you cant select one folder, then try to add another.

**Comment by flleeppyy** [comment]
![Screenshot_20221201-124511_Acode.jpg](https://user-images.githubusercontent.com/18307183/205155878-f3a028d5-ba62-41ef-837e-595cd7591d5f.jpg)

The open folder button disappears when you add a folder, and you can't add any more.

**Comment by SpaghettDev** [comment]
You can actually do that, you just need to click the three dots on the top right, then select Files, then click on the "+", then Add Path, and finally click on select folder and evidently select your desired folder.

<details>
<summary>Here's the step by step, with images:</summary>

- Step 1: Click on the 3 dots.
![image1](https://user-images.githubusercontent.com/37266659/206562008-5c592898-4035-49df-8a34-fb1dbc938d85.jpg)

- Step 2: Click on Files
![image2](https://user-images.githubusercontent.com/37266659/206562178-d94e24ee-c727-45ec-8bbf-f5c82c0c4e55.jpg)

- Step 3: Click on +
![image3](https://user-images.githubusercontent.com/37266659/206562247-25bdf75f-5cbc-4a91-8f95-44d1016ceca8.jpg)

- Step 4: Click on Add Path
![image4](https://user-images.githubusercontent.com/37266659/206562294-4bdaade0-9380-4a1e-a3c8-7b614b2ade92.jpg)

- Step 5: Click select folder
![image5](https://user-images.githubusercontent.com/37266659/206562339-c7bde0ca-79e1-4b9f-8982-25f9506c938e.jpg)

- Step 6: Select the folder, latest versions of Android (10+ I beleive), will not let you open a folder like Downloads (the one in the root, aka /storage/emulated/0/Download) due to it being "not safe"
</details>

**Comment by RaSan147** [comment]
@SpaghettDev well thats not what he meant, 


https://user-images.githubusercontent.com/34002411/218283056-9702ee5f-9d2d-46a3-a5fd-63e3d82593b0.mp4

**Comment by SpaghettDev** [comment]
> @SpaghettDev well thats not what he meant, 
> 
> 
> https://user-images.githubusercontent.com/34002411/218283056-9702ee5f-9d2d-46a3-a5fd-63e3d82593b0.mp4
> 
> 

I'm pretty sure that's what they meant by "having more than one folder" since they said that they had to close the currently opened folder to open another folder.

From what I understood from your video is that you want to have 2 folders' content visible at the same time (as in show the contents of HTML & GUI at the same time). If so, make another feature request since this has no relation to what OP originally posted about.
