### ISSUE TITLE
Cursor offset bug

### ISSUE THREAD

**Issue by bgo-eiu** [deadlyjack/Acode#590]
When editing, as the session goes on there seems to be an increased discrepancy in the cursor position shown and the position new keyboard actions occur. In the example image below, the cursor looks like it is positioned to delete the extra space  before it, but when backspace is pressed, it deletes the quotation mark one position to the right.

![_20221208_091215](https://user-images.githubusercontent.com/100172442/206469215-24133b1c-f433-4f78-b83d-a050fb02075f.JPG)
![_20221208_091303](https://user-images.githubusercontent.com/100172442/206469236-33b85827-e5c7-47dc-bbd4-65a3e660cbb2.JPG)

Sometimes, when the text overflows to display on the next line, the cursor resets and matches the correct position again. Sometimes the offset is different for different lines within a file. I make frequent use of non-ASCII characters and attaching characters/diacritics in the files I edit - that might have something to do with it. It is hard to say though.

**Comment by RaSan147** [comment]
Well nost code editor with monospace font struggle with this. (A Reason to use use monospace: easy to navigate line and column of touched place *since all characters take same space*)

However Unicode fonts make jamble multiple characters in one place *but the editor thinks they are separate and takes equal space*

Its might be a major pain in the back to solve this

**Comment by RaSan147** [comment]
There's a python library "wcwidth"
It can almost accurately determine unicode width. I think this can help by implimenting in JS
