### ISSUE TITLE
[FEATURE REQUEST] Indentation-based Code Folding

### ISSUE THREAD

**Issue by LukeDickerson19** [deadlyjack/Acode#594]
Would it be possible to allow code folding for .txt files as well? Based on indentation.

**Comment by griffi-gh** [comment]
why would anyone need that though?

**Comment by LukeDickerson19** [comment]
its how i organize my notes

**Comment by CodingFan72** [comment]
+1

I use .txt files for organization too: For outlining, planning etc.

Vscode and the text editor of OneDrive Online are able to fold text files by indentation.
And if you use powertools on Windows you can fold text files in the explorer preview too.

It would be great to have something similar on Android. 

At the moment I use the workaround to set yaml as syntax for txt-files.

**Comment by ilias-7565** [comment]
It should be also possible to use indentation-based folding for any language, but just adding it as a language-selection option (to remove the YAML highlighting) can be enough too.
* That folding is much more consistent, and doesn't require language-specific support.
* Syntax checkers are much more complex than that feature, they are more prone to errors and harder to maintain.

In this very moment its impossible to use the app for C# , because folding there doesn't work, due to multiple bugs.

I also suggest to rename this Issue to "Indentation-based folding".
