### ISSUE TITLE
Copy not working 

### ISSUE THREAD

**Issue by LenicoMarak** [deadlyjack/Acode#804]
When i want to copy some text from the editor it is not selecting

**Comment by LenicoMarak** [comment]
V1.8.2

**Comment by LenicoMarak** [comment]
V 1.8.2 (276)

**Comment by deadlyjack** [comment]
Seems to be working for me.

**Comment by edmundlaugasson** [comment]
Using v1.8.7 (330) and can confirm, that copying is still broken but in a bit other way. Usually copying text will cut it instead of copying it. There is a difference, how text is selected. Either manually by dragging appropriate handlings or using select all button from floating toolbar. After trying several times the copying finally somehow succeeds. Veri annoying bug.

**Comment by bajrangCoder** [comment]
It seems like copying working fine
