### ISSUE TITLE
I cannot change file and folder name.

### ISSUE THREAD

**Issue by BloodNTear** [deadlyjack/Acode#955]
Basically I cannot change any file name or folder name within the editor, which makes refactoring the code really hard. I can create new file and everything works fine until I want to rename a file. I am coding reactjs with termux. I use the paid version on google playstore. Please help :"<

P/S: I try looking for app permisson to see if I didn't grant right permisson for it to rename file, but in the settings it shows that acode app doesn't require any permisson
![Screenshot_20240330_174423_Acode](https://github.com/deadlyjack/Acode/assets/91303367/8b3cc3e8-22a8-48c4-ac94-5e2b2e6e6ce2)

**Comment by bajrangCoder** [comment]
Due to termux restrictions or Android limitations, any app can't rename, copy, move folders and files of termux (except read, write, create) . Even your file manager can't do this . You will need to do this from termux terminal using commands. Maybe in future there will something to override but for now option to do this.

## For renaming file/folder through termux 
1. navigate to your file/folder directory using `cd` then use `mv` command to rename .

For example:

```bash
~ $ mv oldname newname 
```

> Just replace oldename and newname placeholder with your actual value

**Comment by BloodNTear** [comment]
Thank you
